# Generated by Django 2.1.5 on 2019-01-17 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Product_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attribute_name', models.CharField(max_length=100)),
                ('Attribute_value', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_logger_app.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_logger_app.Items')),
                ('property_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_logger_app.Property')),
            ],
        ),
    ]
