# Generated by Django 2.1.5 on 2019-01-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_logger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='variant_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
